project:
  type: website

website:
  title: "PS²"
  description: "Philip Skotzke - Performance Science"
  favicon: /images/logo.png
  image: /images/logo.png
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: 
    left: |
      © 2026 Philip Skotzke
    center: |
      Performance Science Squared
    right: |
    #  [Impressum](/impressum/)
  search: false
  navbar:
    right:
      - text: Blog
        href: posts/index.qmd
        icon: vector-pen
      - text: Coaching
        href: coaching/index.qmd
        icon: stopwatch
      - text: About me
        href: about me/index.qmd
      #- text: Mehr
      #  menu: 
      #    - text: Impressum       
      #      href: impressum/
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/philip-skotzke/
        target: _blank
  draft-mode: unlinked
  cookie-consent:
    type: express
    language: de
  google-analytics: G-99JY86FLH4
  
comments:
  giscus: 
    repo: PhilipSkotzke/PerfSci2

format:
  html:
    theme: [cosmo, styles.scss]
    include-after-body: scroll-progress.html